language: node_js
node_js:
  - "node"
branches:
  only:
    - master
git:
  branch: master
before_deploy:
  - npm run build
deploy:
  provider: npm
  tag: next
  api_key: $NPM_TOKEN
  email: $NPM_EMAIL
  on:
    tags: false
    branches:
      - master
